version: "3.1"
services:
  mongo:
    image: "mongo"
    container_name: 'mongodb-integration-tests-sample'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: sample_db
    ports:
        - 27017:27017  